# Generated by Django 5.2.4 on 2025-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.URLField(blank=True, help_text='Second image for product carousel', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.URLField(blank=True, help_text='Third image for product carousel', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.URLField(blank=True, help_text='Fourth image for product carousel', null=True),
        ),
    ]
